comment: true

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        informational: false
        if_ci_failed: error
    patch:
      default:
        target: 100%
        threshold: 0%
        informational: false
        if_ci_failed: error