name: Build Sandbox

on:
  push:
    branches: [main, master]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-sandbox.yml'
      - 'Makefile'
  pull_request:
    branches: [main, master]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-sandbox.yml'
      - 'Makefile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/openhands-custom:latest
            ghcr.io/${{ github.repository }}/openhands-custom:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image
        run: |
          docker pull ghcr.io/${{ github.repository }}/openhands-custom:${{ github.sha }}
          docker run --rm ghcr.io/${{ github.repository }}/openhands-custom:${{ github.sha }} R --version
          docker run --rm ghcr.io/${{ github.repository }}/openhands-custom:${{ github.sha }} python --version
          docker run --rm ghcr.io/${{ github.repository }}/openhands-custom:${{ github.sha }} node --version