# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: Monthly Ubuntu R CMD Check

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:

  R-CMD-check:
    runs-on: ubuntu-latest
    name: Monthly Ubuntu R CMD Check (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {r: 'devel', http-user-agent: 'release'}
          - {r: 'release'}
          - {r: 'oldrel-1'}
          - {r: 'oldrel-2'}
          - {r: 'oldrel-3'}

    steps:
      - uses: actions/checkout@v5
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - run: sudo apt update && sudo apt install tidy
      - run: make check
