name: R CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup R
      uses:  r-lib/actions/setup-r@v2

    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
            extra-packages: any::roxygen2

    - name: Run unit tests
      run: make test

    - name: Run R CMD CHECK
      run: make check

    - name: Run CRAN check
      run: make check-cran
