on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
            extra-packages: any::roxygen2
    - run: make readme
    - name: Check if README.md has changed
      run: |
        if git diff --quiet README.md; then
          echo "README.md is up to date"
        else
          echo "Error: README.md has changed. Please run 'make readme' and commit the changes."
          echo "Diff:"
          git diff README.md
          exit 1
        fi