on:
    workflow_dispatch:
      inputs:
        which:
          type: choice
          description: Which dependents to check
          options:
          - strong
          - most

name: Reverse dependency check
  
jobs:
    revdep_check:
      name: Reverse check ${{ inputs.which }} dependents
      uses: r-devel/recheck/.github/workflows/recheck.yml@ef259e57a8712b89bfb3093a73e082f5fdde79fe # v1
      with:
        which: ${{ inputs.which }}